site_name: BANG
site_author: Axel Springer AI

nav:
    - Home: index.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'SunYanCN/BAND'
repo_url: 'https://github.com/SunYanCN/BAND'

google_analytics:
  - 'UA-137434942-5'
  - 'auto'

markdown_extensions:
  - codehilite