site_name: BAND
site_author: SunYanCN

nav:
    - Home: index.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
    - Documentation:
        - Callbacks: callbacks.md
        - Corpus: corpus.md
        - Utils: utils.md
        - Embeddings:
            - bare_embedding: embeddings/bare_embedding.md
            - base_embedding: embeddings/base_embedding.md
            - bert_embedding: embeddings/bert_embedding.md
            - word_embedding: embeddings/word_embedding.md


theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'SunYanCN/BAND'
repo_url: 'https://github.com/SunYanCN/BAND'

google_analytics:
  - 'UA-137434942-5'
  - 'auto'

markdown_extensions:
  - codehilite